### ISSUE TITLE
randombytes is not support on this plateform

### ISSUE THREAD

**Issue by shatanyumi** [dsprenkels/randombytes#37]
Hi, I write a tiny kernel , I want to port this libs ,  I don't provide /dev/urandom . Could you help me to implement a randmombytes which does not keep any dependence on OS ? thanks very much.

**Comment by dsprenkels** [comment]
@shatanyumi I do not think this is in the scope of this library, because without a kernel there is no standard method to get secure randomness. In those cases you will have to interface with your specific chip's peripheral.

Feel free to send me an email if you're interested in discussing this; or reach out to me in #crypto on irc.libera.chat; or open a stackoverflow question and tag me. :)
